### PR TITLE
adding alias for preact-css-transition group

### PR DESCRIPTION
**Pull request by sarahbethfederman**

### CODE REVIEW

**Comment by notpushkin** [comment]
Hi Sarah, thanks for the contribution! I see that this addon is deprecated in favor of [`react-css-transition`](https://npm.im/react-css-transition), do you think we should create that alias as well? /cc @developit

**Comment by sarahbethfederman** [comment]
Hi @iamale! Thanks for the quick response. I don't think you need the other alias because I believe the newer versions of react will look for lib/ReactTransitionGroup which exists in preact-compat already. What I just added works with the thing I'm aliasing because it uses an older version of react that looks for lib/ReactCSSTransitionGroup :)

**Comment by developit** [comment]
Lovely :)

We might want to duplicate this for all of the existing entries in [preact-compat/lib](https://github.com/developit/preact-compat/tree/master/lib).

**Comment by sarahbethfederman** [comment]
Is there a reason why they wouldn't get those files from the require in index.js?

**Comment by notpushkin** [comment]
@developit Makes sense. Also, maybe it would be better to make a ReactCSSTransitionGroup alias in the preact-compat itself, then? 

@sarahbethfederman `require` don't resolve directories to files, unfortunately (otherwise we could simply have `lib.js` containing `module.exports = require("preact-compat/lib")`).

**Pull request merged**
